Vagrant.configure("2") do |config|

    config.vm.define "podman" do |podman|
        podman.vm.box="shekeriev/almalinux-9.6"
        podman.vm.hostname = "podman.do1.lab"
        podman.vm.network "private_network", ip: "192.168.99.100"
        podman.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
        podman.vm.provision "shell", path: "other-steps.sh"
        podman.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end
    end

  end