services:
  web:
    image: web-image
    deploy:
      mode: global
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - app-network
  php-fpm:
    image: php-image
    deploy:
      mode: global
    volumes:
      - ./web:/var/www/html
    networks:
      - app-network
  db:
    deploy:
      endpoint_mode: dnsrr
    image: db-image
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password

networks:
  app-network:

secrets:
  db_root_password:
    external: true