Vagrant.configure("2") do |config|
  mngr_ip = "192.168.99.105"
  config.vm.synced_folder "./swarm", "/swarm"
  config.vm.synced_folder "../app", "/app"

  config.vm.define "docker1" do |docker1|
    docker1.vm.box = "shekeriev/almalinux-9.6"
    docker1.vm.hostname = "docker5.do1.lab"

    # Corrected port forwarding
    docker1.vm.network "private_network", ip: mngr_ip
    docker1.vm.network "forwarded_port", guest: 22, host: 2222
    docker1.vm.network "forwarded_port", guest: 8080, host: 5080

    # Provision scripts
    docker1.vm.provision "shell", path: "docker-setup.sh"
    docker1.vm.provision "shell", path: "other-steps.sh"
    docker1.vm.provision "shell", path: "docker-images.sh"

    # Inline shell
    docker1.vm.provision "shell", inline: <<-SHELL
        echo "pededasi" > /home/vagrant/pendeli
        docker swarm init --advertise-addr #{mngr_ip} || true
        docker swarm join-token -q worker > /swarm/worker-token.txt
        docker stack rm bgapp_home || true
        echo "<db_root_pass>" | docker secret create db_root_password -
        docker stack deploy -c /home/vagrant/bgapp-homework/docker-compose.yaml bgapp_home

    SHELL

    # VirtualBox memory
    docker1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
  end

  config.vm.define "docker6" do |docker6|
    docker6.vm.box="shekeriev/almalinux-9.6"
    docker6.vm.hostname = "docker6.do1.lab"
    docker6.vm.network "forwarded_port", guest: 22, host: 2226
    docker6.vm.network "forwarded_port", guest: 8080, host: 6080
    docker6.vm.network "private_network", ip: "192.168.99.106"
    docker6.vm.provision "shell", path: "docker-setup.sh"
    docker6.vm.provision "shell", path: "other-steps.sh"
    docker6.vm.provision "shell", path: "docker-images.sh"
    docker6.vm.provision "shell", inline: <<-SHELL
        docker swarm join --token $(cat /swarm/worker-token.txt) #{mngr_ip}:2377 || true
    SHELL
    docker6.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
  end

  config.vm.define "docker7" do |docker7|
    docker7.vm.box="shekeriev/almalinux-9.6"
    docker7.vm.hostname = "docker7.do1.lab"
    docker7.vm.network "forwarded_port", guest: 22, host: 2227
    docker7.vm.network "forwarded_port", guest: 8080, host: 7080
    docker7.vm.network "private_network", ip: "192.168.99.107"
    docker7.vm.provision "shell", path: "docker-setup.sh"
    docker7.vm.provision "shell", path: "other-steps.sh"
    docker7.vm.provision "shell", path: "docker-images.sh"
    docker7.vm.provision "shell", inline: <<-SHELL
        docker swarm join --token $(cat /swarm/worker-token.txt) #{mngr_ip}:2377 || true
    SHELL
    docker7.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
  end

end
