Vagrant.configure("2") do |config|

    config.vm.define "docker1" do |docker1|
        docker1.vm.box="shekeriev/almalinux-9.6"
        docker1.vm.hostname = "docker5.do1.lab"
        docker1.vm.network "private_network", ip: "192.168.99.105"
        docker1.vm.provision "shell", path: "docker-setup.sh"
        docker1.vm.provision "shell", path: "other-steps.sh"
        docker1.vm.provision "shell", path: "docker-images.sh"
        docker1.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1536"]
        end
    end

  end
